#!/bin/bash
source ./VARIABLE.sh

#######################   For First time
# sudo apt-get install moreutils

# Common path
Target_PATH="."
LOG_PATH="$Target_PATH/LOG"
LOCKFILE="$Target_PATH/tmp-build_run.lock"

mkdir -p "$LOG_PATH"

# Check if the lock file exists
if [ -e $LOCKFILE ]; then
    echo "Another user is currently building and running the code. Please wait."
    exit 1
else
    bash "$Target_PATH/exit"
    # Create the lock file
    touch $LOCKFILE
    echo "Set ifconfig"
    ./set-ifconfig
    # echo "execute OAI Core Network"
    # ./cn
    sudo echo "Start TCPdump..."
    sudo tcpdump -i lo -nn '(proto SCTP) or (proto UDP)' -w $LOG_PATH/nFAPI_TCPdump.pcap &
    echo "execute OAI VNF"
    stdbuf -oL ./vnf 2>&1 | ts &> "$LOG_PATH/VNF-nfapi-fixes.log" &
    echo "execute OAI PNF"
    stdbuf -oL ./pnf 2>&1 | ts &> "$LOG_PATH/PNF-nfapi-fixes.log" &
    echo "execute OAI UE"
    stdbuf -oL ./ue 2>&1 | ts &> "$LOG_PATH/UE-nfapi-fixes.log" &
    # bash "./ping-autoExecute" &
    # bash "./iperf-client-autoExecute" &

    wait_sec=50
    echo "The script automatically closes after $wait_sec seconds..."
    ####################### Wait for the specified number of seconds
    sleep $wait_sec
    bash "$Target_PATH/exit"
    echo "Time to $wait_sec seconds..."
    # kill $!
    echo "END"
    # # Remove the lock file
    # rm $LOCKFILE
fi