#!/bin/bash
UE_IP=$(bash "./iperf-client-autoExecute")
iperf3 -B $UE_IP -c 192.168.70.135 -t 5 -R
# iperf3 -c 192.168.70.135 -B 10.0.0.2 -t 40 -R -b100M # TCP, reverse -> TCP in DL from server to client
# iperf3 ... -t 40 -b1M -u # UDP in UL from client to server