#!/bin/bash
source ./VARIABLE.sh
cd $PATH_TO_UE
cd ./cmake\_targets/ran\_build/build
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --sa --uicc0.imsi 001010000000001 --rfsim
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.conf
sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --uicc0.imsi 001010000000001 --rfsim 
# --log_config.global_log_options level --log_config.global_log_level DEBUG