#!/bin/bash
source ./VARIABLE.sh
cd $PATH_TO_UE
cd ./cmake\_targets/ran\_build/build
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 -O $PATH_TO_SCRIPT/CONFIG/ue.conf

# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --sa --uicc0.imsi 001010000000001 --rfsim
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.conf
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.conf
# --log_config.global_log_options level --log_config.global_log_level DEBUG
# work
# sudo ./nr-uesoftmodem --rfsim --rfsimulator.serveraddr 127.0.0.1 -r 106 --numerology 1 --band 78 -C 3619200000 -O ../../../targets/PROJECTS/GENERIC-NR-5GC/CONF/ue.conf
sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --uicc0.imsi 001010000000001 --rfsim 
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 -O $PATH_TO_SCRIPT/CONFIG/ue.conf --rfsim 
# --uicc0.imsi 001010000062653 --uicc0.key 8baf473f2f8fd09487cccbd7097c6862 --uicc0.opc 8e27b6af0e692e750f32667a3b14605d  --uicc0.dnn internet

# For BMW lab open5GS CN
# sudo ./nr-uesoftmodem -r 106 --numerology 1 --band 78 -C 3619200000 --ssb 516 --rfsim --uicc0.imsi 001010000000001 --uicc0.key fec86ba6eb707ed08905757b1bb44b8f --uicc0.opc C42449363BBAD02B66D16BC975D77CC1 --uicc0.dnn internet --rfsimulator.serveraddr 127.0.0.1