BASE_PATH="/home/$(whoami)"
export PATH_TO_openairinterface5g="$BASE_PATH/OnlyOAI/openairinterface5g"
export PATH_TO_PNF="$BASE_PATH/OnlyOAI/openairinterface5g"
export PATH_TO_UE="$BASE_PATH/OnlyOAI/openairinterface5g"
export PATH_TO_SCRIPT="$BASE_PATH/OnlyOAI/nfapi-split-script"
