#!/bin/bash
source ./VARIABLE.sh
cd $PATH_TO_openairinterface5g
cd ./cmake\_targets/ran\_build/build
sudo LD_LIBRARY_PATH=./ NFAPI\_TRACE\_LEVEL=info ./nr-softmodem -O ../../../targets/PROJECTS/GENERIC-LTE-EPC/CONF/rcc.band78.tm1.106PRB.nfapi.conf --nfapi VNF --sa --log\_config.global\_log\_options wall\_clock --emulate-l1 #--MACRLCs.[0].ulsch_max_frame_inactivity 0
